In [1]:
import pandas as pd
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("C:/Users/Administrator/Desktop/arduino/DRDO/Test datasets/Sumukha _21 - Copy.csv")
df

,0,1,2,3,4,5,6,7,8,9,...,992,993,994,995,996,997,998,999,label,EMG
0,105,-29,-137,15,90,20,-122,112,22,-11,...,39,-128,43,85,-5,-112,127,-14,cylindrical,EMG1
1,-29,-76,79,10,-59,-25,89,32,-121,73,...,-100,95,2,-33,-49,84,44,-131,cylindrical,EMG1
2,21,97,-5,-117,124,-8,-34,-65,81,27,...,-8,-27,-76,79,15,-61,-26,90,cylindrical,EMG1
3,34,-122,68,36,-14,-105,100,-3,-34,-51,...,-115,122,-9,-37,-65,81,27,-93,cylindrical,EMG1
4,-11,94,18,-121,109,11,-26,-89,87,8,...,59,-13,-109,109,-4,-38,-56,83,cylindrical,EMG1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,-85,-68,100,45,-100,-9,112,-13,-120,55,...,126,-82,-106,102,58,-111,-20,123,tip,EMG3
536,2,-126,47,127,-78,-114,99,68,-112,-27,...,46,-114,-8,124,-21,-133,65,123,tip,EMG3
537,-90,-86,109,52,-113,-14,125,-12,-129,62,...,-31,-134,84,100,-108,-43,113,32,tip,EMG3
538,-119,1,135,-22,-142,89,88,-83,-56,93,...,-100,-15,118,-21,-135,56,130,-89,tip,EMG3
539,-99,107,65,-100,-22,121,-5,-129,47,124,...,-50,-136,81,94,-98,-57,110,41,tip,EMG3

In [3]:
df_features_ch1 = df[df['label'] == 'cylindrical']
df_features_ch1

,0,1,2,3,4,5,6,7,8,9,...,992,993,994,995,996,997,998,999,label,EMG
0,105,-29,-137,15,90,20,-122,112,22,-11,...,39,-128,43,85,-5,-112,127,-14,cylindrical,EMG1
1,-29,-76,79,10,-59,-25,89,32,-121,73,...,-100,95,2,-33,-49,84,44,-131,cylindrical,EMG1
2,21,97,-5,-117,124,-8,-34,-65,81,27,...,-8,-27,-76,79,15,-61,-26,90,cylindrical,EMG1
3,34,-122,68,36,-14,-105,100,-3,-34,-51,...,-115,122,-9,-37,-65,81,27,-93,cylindrical,EMG1
4,-11,94,18,-121,109,11,-26,-89,87,8,...,59,-13,-109,109,-4,-38,-56,83,cylindrical,EMG1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,-94,-109,125,19,-111,78,54,50,-108,124,...,62,27,50,-101,114,35,-41,-131,cylindrical,EMG3
386,113,21,-106,61,30,49,-102,113,35,-31,...,50,-104,122,52,-106,-154,108,22,cylindrical,EMG3
387,-113,68,47,56,-103,121,45,-97,-156,104,...,114,42,-111,81,44,68,-101,125,cylindrical,EMG3
388,41,-96,-107,108,41,-110,79,44,71,-101,...,-114,119,42,-110,78,43,69,-102,cylindrical,EMG3
389,124,42,-97,-112,119,42,-110,78,43,68,...,-77,-152,110,24,-111,65,45,52,cylindrical,EMG3

In [4]:
df_labels = df['label']
df_labels

0      cylindrical
1      cylindrical
2      cylindrical
3      cylindrical
4      cylindrical
          ...
535            tip
536            tip
537            tip
538            tip
539            tip
Name: label, Length: 540, dtype: object

In [5]:
df_features_ch1 = df_features_ch1.drop(columns=['label','EMG'],axis=1)
df_features_ch1

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,105,-29,-137,15,90,20,-122,112,22,-11,...,-36,85,39,-128,43,85,-5,-112,127,-14
1,-29,-76,79,10,-59,-25,89,32,-121,73,...,27,-17,-100,95,2,-33,-49,84,44,-131
2,21,97,-5,-117,124,-8,-34,-65,81,27,...,-118,131,-8,-27,-76,79,15,-61,-26,90
3,34,-122,68,36,-14,-105,100,-3,-34,-51,...,88,-8,-115,122,-9,-37,-65,81,27,-93
4,-11,94,18,-121,109,11,-26,-89,87,8,...,-123,50,59,-13,-109,109,-4,-38,-56,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,-94,-109,125,19,-111,78,54,50,-108,124,...,22,-107,62,27,50,-101,114,35,-41,-131
386,113,21,-106,61,30,49,-102,113,35,-31,...,64,48,50,-104,122,52,-106,-154,108,22
387,-113,68,47,56,-103,121,45,-97,-156,104,...,-97,-99,114,42,-111,81,44,68,-101,125
388,41,-96,-107,108,41,-110,79,44,71,-101,...,42,-96,-114,119,42,-110,78,43,69,-102
389,124,42,-97,-112,119,42,-110,78,43,68,...,119,45,-77,-152,110,24,-111,65,45,52

In [6]:
encoder = LabelEncoder()

In [7]:
encoder.fit(df_labels)

LabelEncoder()

In [8]:
df_labels

0      cylindrical
1      cylindrical
2      cylindrical
3      cylindrical
4      cylindrical
          ...
535            tip
536            tip
537            tip
538            tip
539            tip
Name: label, Length: 540, dtype: object

In [9]:
encoded_y = encoder.transform(df_labels)

In [10]:
encoded_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
y = np_utils.to_categorical(encoded_y)

In [12]:
y

array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [27]:
y.shape

(540, 6)

In [15]:
x = np.array(df_features_ch1[:])
x = x.reshape(x.shape[0],x.shape[1],1)
x = np.asarray(x).astype(np.float32)
x

array([[[ 105.],
        [ -29.],
        [-137.],
        ...,
        [-112.],
        [ 127.],
        [ -14.]],

       [[ -29.],
        [ -76.],
        [  79.],
        ...,
        [  84.],
        [  44.],
        [-131.]],

       [[  21.],
        [  97.],
        [  -5.],
        ...,
        [ -61.],
        [ -26.],
        [  90.]],

       ...,

       [[-113.],
        [  68.],
        [  47.],
        ...,
        [  68.],
        [-101.],
        [ 125.]],

       [[  41.],
        [ -96.],
        [-107.],
        ...,
        [  43.],
        [  69.],
        [-102.]],

       [[ 124.],
        [  42.],
        [ -97.],
        ...,
        [  65.],
        [  45.],
        [  52.]]], dtype=float32)

In [16]:
len(x)

90

In [17]:
df_features_ch2 = df[df['label'] == 'cylindrical']
df_features_ch2

,0,1,2,3,4,5,6,7,8,9,...,992,993,994,995,996,997,998,999,label,EMG
0,105,-29,-137,15,90,20,-122,112,22,-11,...,39,-128,43,85,-5,-112,127,-14,cylindrical,EMG1
1,-29,-76,79,10,-59,-25,89,32,-121,73,...,-100,95,2,-33,-49,84,44,-131,cylindrical,EMG1
2,21,97,-5,-117,124,-8,-34,-65,81,27,...,-8,-27,-76,79,15,-61,-26,90,cylindrical,EMG1
3,34,-122,68,36,-14,-105,100,-3,-34,-51,...,-115,122,-9,-37,-65,81,27,-93,cylindrical,EMG1
4,-11,94,18,-121,109,11,-26,-89,87,8,...,59,-13,-109,109,-4,-38,-56,83,cylindrical,EMG1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,-94,-109,125,19,-111,78,54,50,-108,124,...,62,27,50,-101,114,35,-41,-131,cylindrical,EMG3
386,113,21,-106,61,30,49,-102,113,35,-31,...,50,-104,122,52,-106,-154,108,22,cylindrical,EMG3
387,-113,68,47,56,-103,121,45,-97,-156,104,...,114,42,-111,81,44,68,-101,125,cylindrical,EMG3
388,41,-96,-107,108,41,-110,79,44,71,-101,...,-114,119,42,-110,78,43,69,-102,cylindrical,EMG3
389,124,42,-97,-112,119,42,-110,78,43,68,...,-77,-152,110,24,-111,65,45,52,cylindrical,EMG3

In [18]:
data_features = df_features_ch2.drop(columns=['label','EMG'],axis=1)
data_features

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,105,-29,-137,15,90,20,-122,112,22,-11,...,-36,85,39,-128,43,85,-5,-112,127,-14
1,-29,-76,79,10,-59,-25,89,32,-121,73,...,27,-17,-100,95,2,-33,-49,84,44,-131
2,21,97,-5,-117,124,-8,-34,-65,81,27,...,-118,131,-8,-27,-76,79,15,-61,-26,90
3,34,-122,68,36,-14,-105,100,-3,-34,-51,...,88,-8,-115,122,-9,-37,-65,81,27,-93
4,-11,94,18,-121,109,11,-26,-89,87,8,...,-123,50,59,-13,-109,109,-4,-38,-56,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,-94,-109,125,19,-111,78,54,50,-108,124,...,22,-107,62,27,50,-101,114,35,-41,-131
386,113,21,-106,61,30,49,-102,113,35,-31,...,64,48,50,-104,122,52,-106,-154,108,22
387,-113,68,47,56,-103,121,45,-97,-156,104,...,-97,-99,114,42,-111,81,44,68,-101,125
388,41,-96,-107,108,41,-110,79,44,71,-101,...,42,-96,-114,119,42,-110,78,43,69,-102
389,124,42,-97,-112,119,42,-110,78,43,68,...,119,45,-77,-152,110,24,-111,65,45,52

In [20]:
data_labels = df_features_ch2['label']
data_labels

0      cylindrical
1      cylindrical
2      cylindrical
3      cylindrical
4      cylindrical
          ...
385    cylindrical
386    cylindrical
387    cylindrical
388    cylindrical
389    cylindrical
Name: label, Length: 90, dtype: object

In [33]:
encoder.fit(data_labels)
encoded_sy = np.array(encoder.transform(data_labels))
print(encoded_sy)
sy = np_utils.to_categorical(encoded_sy)
print(sy.shape)
sy = np.reshape(sy, (-1, 6))
sy.shape

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(90, 1)

(15, 6)

In [54]:
df = pd.read_excel('D:/project/DRDO/ML_gui_v2/Data Collection 07072023/Sumant/RH/SumantRH07072023_cylindrical.xlsx')
df

       EMG 1  EMG 2  EMG 3
0        332    288   -312
1       -166     79    -48
2        -44    -31    -54
3        -73    -62    -30
4         10     17     31
...      ...    ...    ...
29996    -11      5      6
29997    -12     -6      2
29998      8     -4     -3
29999     10      7     -1
30000    -11      6      5

[30001 rows x 3 columns]

In [55]:
# Function to split each column into rows of 1000 values
def split_into_rows(column, sensor_name):
    num_rows = len(column) // 1000
    data_rows = [column[i * 1000: (i + 1) * 1000] for i in range(num_rows)]
    return [(sensor_name, row) for row in data_rows]

# Create a new DataFrame with data in the desired format
new_data = []
for col_name in df.columns:
    sensor_name = col_name
    sensor_values = df[col_name].values
    new_data.extend(split_into_rows(sensor_values, sensor_name))

result_df = pd.DataFrame(new_data, columns=['sensor_name', 'sensor_data'])

# Print the resulting DataFrame
result_df

   sensor_name                                        sensor_data
0        EMG 1  [332, -166, -44, -73, 10, 51, -22, -19, 37, 13...
1        EMG 1  [-10, -4, 15, 8, -10, -4, 14, 9, -11, -5, 15, ...
2        EMG 1  [14, 5, -11, -3, 14, 6, -11, -1, 14, 6, -10, -...
3        EMG 1  [-11, -1, 15, 5, -11, -2, 15, 5, -12, -1, 14, ...
4        EMG 1  [14, -9, -10, 10, 14, -9, -10, 11, 14, -10, -1...
..         ...                                                ...
85       EMG 3  [5, 1, -5, -2, 5, 1, -4, 0, 5, 0, -4, -1, 5, 1...
86       EMG 3  [6, 0, -3, -1, 5, 1, -3, -1, 5, 1, -4, -1, 5, ...
87       EMG 3  [5, 2, -3, -1, 6, 3, -3, -1, 5, 2, -3, 0, 5, 3...
88       EMG 3  [5, 2, -3, -2, 5, 3, -3, -2, 5, 3, -4, -1, 5, ...
89       EMG 3  [6, 2, -3, 0, 6, 3, -3, -1, 6, 2, -2, -1, 5, 2...

[90 rows x 2 columns]

In [56]:
# Function to split each column into rows of 1000 values
def split_into_rows(column, sensor_name):
    num_rows = len(column) // 1000
    data_rows = [column[i * 1000: (i + 1) * 1000] for i in range(num_rows)]
    return [(sensor_name, row) for row in data_rows]

# Create a new DataFrame with data in the desired format
new_data = []
for col_name in df.columns:
    sensor_name = col_name
    sensor_values = df[col_name].values
    new_data.extend(split_into_rows(sensor_values, sensor_name))

result_df = pd.DataFrame(new_data, columns=['sensor_name', 'sensor_data'])

# Split 'sensor_data' into respective columns
result_df = pd.DataFrame(result_df['sensor_data'].tolist(), index=result_df['sensor_name']).reset_index()

# Print the resulting DataFrame
result_df.rename(columns={'sensor_name': 'EMG'}, inplace=True)
result_df = result_df.assign(label='cylindrical')

result_df

,EMG,0,1,2,3,4,5,6,7,8,...,991,992,993,994,995,996,997,998,999,label
0,EMG 1,332,-166,-44,-73,10,51,-22,-19,37,...,8,-10,-4,15,8,-11,-4,15,9,cylindrical
1,EMG 1,-10,-4,15,8,-10,-4,14,9,-11,...,-1,14,4,-10,0,15,6,-11,-1,cylindrical
2,EMG 1,14,5,-11,-3,14,6,-11,-1,14,...,5,-11,-1,16,6,-11,-1,16,5,cylindrical
3,EMG 1,-11,-1,15,5,-11,-2,15,5,-12,...,12,14,-9,-10,11,13,-8,-9,11,cylindrical
4,EMG 1,14,-9,-10,10,14,-9,-10,11,14,...,-11,-8,13,11,-11,-8,13,11,-10,cylindrical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,EMG 3,5,1,-5,-2,5,1,-4,0,5,...,0,5,1,-4,-1,6,1,-4,-1,cylindrical
86,EMG 3,6,0,-3,-1,5,1,-3,-1,5,...,-1,5,3,-4,-2,5,2,-2,-1,cylindrical
87,EMG 3,5,2,-3,-1,6,3,-3,-1,5,...,-1,5,1,-3,-1,5,3,-3,-1,cylindrical
88,EMG 3,5,2,-3,-2,5,3,-3,-2,5,...,0,5,2,-4,-1,5,1,-4,-1,cylindrical
89,EMG 3,6,2,-3,0,6,3,-3,-1,6,...,-1,5,2,-3,-1,6,2,-3,-1,cylindrical

In [57]:
file_names = [
    'SumantRH07072023_hook.xlsx',
    'SumantRH07072023_Lateral.xlsx',
    'SumantRH07072023_Palmar.xlsx',
    'SumantRH07072023_Spherical.xlsx',
    'SumantRH07072023_Tip.xlsx'
]
frames = [result_df]
for file in file_names:
    dh = pd.read_excel(f"D:/project/DRDO/ML_gui_v2/Data Collection 07072023/Sumant/RH/{file}")
    file_name_without_extension = file.split('.')[0]  # Remove the file extension (".xlsx")
    action_name = file_name_without_extension.split('_')[-1]
    # Function to split each column into rows of 1000 values
    def split_into_rows(column, sensor_name):
        num_rows = len(column) // 1000
        data_rows = [column[i * 1000: (i + 1) * 1000] for i in range(num_rows)]
        return [(sensor_name, row) for row in data_rows]

    # Create a new DataFrame with data in the desired format
    new_data = []
    for col_name in dh.columns:
        sensor_name = col_name
        sensor_values = dh[col_name].values
        new_data.extend(split_into_rows(sensor_values, sensor_name))

    result_df_new = pd.DataFrame(new_data, columns=['sensor_name', 'sensor_data'])

    # Split 'sensor_data' into respective columns
    result_df_new = pd.DataFrame(result_df_new['sensor_data'].tolist(), index=result_df_new['sensor_name']).reset_index()

    # Print the resulting DataFrame
    result_df_new.rename(columns={'sensor_name': 'EMG'}, inplace=True)
    result_df_new = result_df_new.assign(label=action_name)
    frames.append(result_df_new)
    print(result_df_new)

combined_data = pd.concat(frames)  
combined_data

      EMG    0    1   2   3   4   5   6   7   8  ...  991  992  993  994  995  \
0   EMG 1  325 -166 -43 -82  -2  44 -23 -26  26  ...   -8  -16    0    8   -8
1   EMG 1  -16   -1   8  -7 -16  -1   8  -6 -16  ...    7    3  -16  -11    6
2   EMG 1    4  -16 -11   8   5 -16 -12   6   5  ...  -16    5    7  -16  -17
3   EMG 1    4    9 -14 -17   3   8 -15 -18   3  ...  -18  -15    6    5  -17
4   EMG 1  -15    8   7 -17 -16   6   7 -17 -15  ...    6  -17  -15    7    6
..    ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
85  EMG 3    0    5   7   1  -1   5   7   1   0  ...    9    4    0    2    8
86  EMG 3    4   -1   2   9   4  -2   2   8   4  ...    2    9    5   -1    1
87  EMG 3    8    5  -1   1   9   6   0   1   9  ...    1    0    5    7    1
88  EMG 3    0    5   9   2   0   5   8   3   0  ...    9    4   -1    1    8
89  EMG 3    5    0   2   8   6   0   1   8   6  ...    0    5    7    2    0

    996  997  998  999  label
0   -16   -1    9   -8   hook
1     3  -16  -11    6   hook
2     4    7  -15  -18   hook
3   -15    8    7  -16   hook
4   -17  -15    7    5   hook
..  ...  ...  ...  ...    ...
85    4   -1    3    9   hook
86    9    5    0    1   hook
87    0    5    8    2   hook
88    5   -1    0    8   hook
89    6    7    1    0   hook

[90 rows x 1002 columns]
      EMG    0    1   2   3   4   5  6   7   8  ...  991  992  993  994  995  \
0   EMG 1  322 -181 -23 -69 -22  30 -4 -18   3  ...    0  -19  -12    7    1
1   EMG 1  -19  -11   7   1 -19 -11  6   0 -19  ...    1  -19  -13    6    2
2   EMG 1  -19  -12   6   2 -18 -13  7   1 -19  ...    3  -20  -14    6    3
3   EMG 1  -18  -14   5   3 -18 -14  7   2 -19  ...    1  -18  -13    6    1
4   EMG 1  -19  -12   7   2 -19 -13  6   1 -19  ...    1  -19  -12    6    2
..    ...  ...  ...  ..  ..  ..  .. ..  ..  ..  ...  ...  ...  ...  ...  ...
85  EMG 3    9    4   0   3   9   3  0   4   8  ...    4   10    4    0    3
86  EMG 3    9    4   0   3   9   4  0   2   8  ...    4    8    3    0    4
87  EMG 3    8    3   0   3   9   4  0   5   9  ...    5    8    2    0    5
88  EMG 3    8    3   0   5   8   4  0   3   8  ...    3    9    4    0    3
89  EMG 3    9    3   0   3   8   4  0   4   9  ...    3    9    4    0    3

    996  997  998  999    label
0   -19  -12    6    0  Lateral
1   -18  -12    6    1  Lateral
2   -19  -15    7    3  Lateral
3   -19  -13    6    1  Lateral
4   -19  -12    7    1  Lateral
..  ...  ...  ...  ...      ...
85    9    3    0    3  Lateral
86    8    4    0    4  Lateral
87    8    2    0    4  Lateral
88    9    4    0    4  Lateral
89    8    4   -1    3  Lateral

[90 rows x 1002 columns]
      EMG    0    1   2   3   4   5   6   7   8  ...  991  992  993  994  995  \
0   EMG 1  323 -164 -31 -84 -13  45 -12 -29  13  ...   -7  -18   -5    7   -5
1   EMG 1  -19   -6   8  -4 -19  -7   8  -2 -18  ...    7    0  -18  -11    8
2   EMG 1    0  -18 -10   7   0 -18 -11   7   0  ...  -12    7    2  -18  -13
3   EMG 1    7    2 -17 -13   7   3 -17 -13   6  ...  -17  -14    6    5  -18
4   EMG 1  -15    6   5 -18 -16   6   6 -18 -15  ...    7  -15  -17    2    7
..    ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
85  EMG 3    4    8   4  -1   4   8   4   0   4  ...    7    2    0    7    7
86  EMG 3    1    0   6   8   1   0   6   7   2  ...    3    9    5    0    2
87  EMG 3   10    4   0   2   9   5  -1   2   9  ...    0    0    9    7    0
88  EMG 3    1    8   6   0   0   8   7   1   0  ...    8    1    0    6    8
89  EMG 3    2    0   5   8   1   0   5   8   2  ...    6    7    1    0    6

    996  997  998  999   label
0   -18   -5    7   -5  Palmar
1     0  -18  -11    7  Palmar
2     5    3  -19  -13  Palmar
3   -15    5    5  -17  Palmar
4   -15  -18    1    7  Palmar
..  ...  ...  ...  ...     ...
85    0    0    7    7  Palmar
86   10    5   -1    2  Palmar
87    1    9    7    0  Palmar
88    1    0    6    7  Palmar
89    9    3    0    6  Palmar

[90 rows x 1002 columns]
      EMG    0    1   2   3   4   5   6   7   8  ...  991  992  993  994  995  \
0   EMG 1  323 -193 -48 -61   3  20 -27  -8  29  ...   -7    8   -5  -19   -7
1   EMG 1    7   -2 -20 -11   7  -1 -19 -10   7  ...  -18    2    8  -16  -19
2   EMG 1    1    7 -14 -18   0   7 -13 -18   0  ...  -17  -17    5    6  -18
3   EMG 1  -17    5   7 -16 -17   5   7 -16 -17  ...    5  -18  -15    5    5
4   EMG 1  -18  -17   5   5 -18 -16   5   5 -17  ...    6    3  -19  -15    6
..    ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
85  EMG 3   -1    2   9   4   0   3   8   5   0  ...    3    9    4    0    4
86  EMG 3   10    4   0   4   9   4   0   3   9  ...    0    2   10    5    0
87  EMG 3    2   10   5   0   1   8   5  -1   1  ...   10    4    0    2    9
88  EMG 3    5   -1   3   9   5   0   3   9   4  ...    9    5   -1    4    9
89  EMG 3    5    0   2   9   4  -1   2   9   5  ...    9    4    0    2    8

    996  997  998  999      label
0     7   -3  -19   -9  Spherical
1     1    6  -14  -18  Spherical
2   -16    5    6  -17  Spherical
3   -18  -17    5    5  Spherical
4     4  -19  -15    6  Spherical
..  ...  ...  ...  ...        ...
85   10    4    0    3  Spherical
86    1   10    6    0  Spherical
87    4    0    2    8  Spherical
88    6    0    2    9  Spherical
89    3   -1    2    8  Spherical

[90 rows x 1002 columns]
      EMG    0    1   2   3   4   5   6   7   8  ...  991  992  993  994  995  \
0   EMG 1  328 -179 -21 -71 -16  38   0 -17   8  ...   -2  -14   -2   10   -1
1   EMG 1  -15   -3  11  -1 -15  -2  10  -2 -15  ...   10  -11  -12    6   10
2   EMG 1  -11  -14   6   9 -11 -14   5  10 -11  ...   10  -12  -13    5    9
3   EMG 1  -12  -13   5   9 -12 -13   5   9 -11  ...   10  -12  -15    4   10
4   EMG 1  -12  -14   6  11 -11 -14   6   9 -12  ...   10  -12  -14    5   10
..    ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
85  EMG 3   -1    0   7   4   0   0   6   4  -2  ...    0   -1    5    6    0
86  EMG 3    0    5   6   1  -1   4   5   0  -1  ...   -2    2    7    3   -1
87  EMG 3    2    6   2  -1   2   6   1  -2   2  ...    0    7    4   -1    0
88  EMG 3    6    3  -2   0   6   3  -1   0   7  ...    6    4    0    0    6
89  EMG 3    4   -1   0   5   5   0   0   5   5  ...    7    3   -2    1    7

    996  997  998  999  label
0   -14   -3   11   -1    Tip
1   -11  -13    6    9    Tip
2   -12  -14    6   10    Tip
3   -12  -15    4    9    Tip
4   -11  -14    5    9    Tip
..  ...  ...  ...  ...    ...
85   -2    5    6    0    Tip
86    2    7    2   -1    Tip
87    7    5   -1    0    Tip
88    3    0    0    5    Tip
89    3   -2    1    8    Tip

[90 rows x 1002 columns]

,EMG,0,1,2,3,4,5,6,7,8,...,991,992,993,994,995,996,997,998,999,label
0,EMG 1,332,-166,-44,-73,10,51,-22,-19,37,...,8,-10,-4,15,8,-11,-4,15,9,cylindrical
1,EMG 1,-10,-4,15,8,-10,-4,14,9,-11,...,-1,14,4,-10,0,15,6,-11,-1,cylindrical
2,EMG 1,14,5,-11,-3,14,6,-11,-1,14,...,5,-11,-1,16,6,-11,-1,16,5,cylindrical
3,EMG 1,-11,-1,15,5,-11,-2,15,5,-12,...,12,14,-9,-10,11,13,-8,-9,11,cylindrical
4,EMG 1,14,-9,-10,10,14,-9,-10,11,14,...,-11,-8,13,11,-11,-8,13,11,-10,cylindrical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,EMG 3,-1,0,7,4,0,0,6,4,-2,...,0,-1,5,6,0,-2,5,6,0,Tip
86,EMG 3,0,5,6,1,-1,4,5,0,-1,...,-2,2,7,3,-1,2,7,2,-1,Tip
87,EMG 3,2,6,2,-1,2,6,1,-2,2,...,0,7,4,-1,0,7,5,-1,0,Tip
88,EMG 3,6,3,-2,0,6,3,-1,0,7,...,6,4,0,0,6,3,0,0,5,Tip
89,EMG 3,4,-1,0,5,5,0,0,5,5,...,7,3,-2,1,7,3,-2,1,8,Tip

In [58]:
combined_data['EMG'] = combined_data['EMG'].str.replace(' ','')
combined_data.to_csv('Sumant_RH.csv')